// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/testtimer_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// nothing
void nothing();
RcppExport SEXP _testtimer_nothing() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    nothing();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testtimer_nothing", (DL_FUNC) &_testtimer_nothing, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_testtimer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
